let exerNum = 1

function print(...args) {
    console.log(...args)
}

function prinln() {
    print(`----------${exerNum}----------`)
    exerNum++
}


function dashes() {
    print('------------------------------')
}


/**
 * 01
 * Create an array with objects
 * 
 * Each object should contain all necessary data for a blog post
 * such as title, text, comments, author, description, id and others.
 * The array should have at least 3 blog posts
 * 
 * Create a function that will search a text in all text properties and
 * return the results in an array or the text 'No matching posts found' if there 
 * are no matching posts
 * 
 * Create a function that edits a given post. The user should be able to edit 
 * any object property he would like and should return the updated object
 * If the post is not found then the function should return 'Post not found'
 * 
 * create a function that deletes a post with a given id from the array 
 * and returns the updated array
 * 
 * create a function that displays the comments of a given post one per row
 */
// Sample Data


// * 01
// * Create an array with objects
// * 
// * Each object should contain all necessary data for a blog post
// * such as title, text, comments, author, description, id and others.
// * The array should have at least 3 blog posts



const blogPosts = [{
        id: 1,
        title: 'The AI in military',
        text: `And when the time he was in front of the army were cut short.
        The horse would have been trampled to pieces,
        
        And the men who would have been killed, and the whole town would have been burned.
        
        But I have been there, and we are done, for the king has gone forward,
        
        And if he is still in front of us, it says that it is time for him to see it again.
        
        Now let us come back to the place,
        
        For our own sake I will take an oath.
        
        Then shall we come back and lay hands on their bodies,
        
        And all that has no other will be eaten
        
        And there will be a thousand thousand more people to be massacred.
        
        Now let us go and lay hands on theirs.`,
        author: 'deepai.org',
        description: 'text generated from a machine in deepai.org',
        comments: ['Awesome posts, thanks!', 'Cannot agree more']
    },
    {
        id: 2,
        title: 'A garden in Babylon',
        text: `As a result, the first of the ten disciples of Samaria, 
        called the "Tray-Bearer of Wisdom," was known by her as the 
        "Empire of the Tungis." 
        The Tungis are the divine spirits of the Dead and of the Prophets. 
        She taught these beings that in every person who does not know any of them,
         all they can do is to look for a spirit that has been placed at the root 
         of any man's estate. She even stated this to the Prophet Joseph.`,
        author: 'deepai.org',
        description: 'text generated from a machine in deepai.org',
        comments: ['Amazed wow!', 'I dislike that']
    },
    {
        id: 3,
        title: 'Here goes the title',
        text: 'Lorem Ipsom',
        author: 'Me',
        description: 'Text generated by me from my brain',
        comment: ['Amazed wow!', 'I dislike that']
    }
]


// Create a function that will search a text in all text properties and
//  * return the results in an array or the text 'No matching posts found' if there 
//  * are no matching posts
prinln()

// function findText(array, textToFound) {
//     let foundWord = []
//     let notFound = ''
//     array.forEach(element => {
//         (element.text).includes(textToFound) ? foundWord.push(element.text) : notFound = 'No matching posts found'
//             // print(element.text)
//             // for (const key in element) {
//             //     print(element[key])
//             // }
//     });
//     return foundWord.length > 0 ? foundWord : notFound
// }
//--------------------------------
// Create a function that will search a text in all text properties and
//  * return the results in an array or the text 'No matching posts found' if there 
//  * are no matching posts

function searchText(array, textToFound) {
    let result = [];

    array.forEach(george => {
        if (george.text.includes(textToFound)) result.push(george)
    })

    if (result.length > 0) return result

    return 'Not found'
        // return result.length > 0 ? result : 'Not Found'
}

// print(findText(blogPosts, 'beings'))
print(searchText(blogPosts, 'beingssoman'))
print(searchText(blogPosts, 'man'))



// * Create a function that edits a given post. The user should be able to edit 
// * any object property he would like and should return the updated object
// * If the post is not found then the function should return 'Post not found'

prinln()

// function updatePost(ids, index, newInput) {
//     notFound = false
//     blogPosts.forEach(element => {
//         element.id !== ids ? notFound = true : ''
//         print(element.id + 1 === ids)
//     });

//     return notFound ? 'Post not Found' : blogPosts
// }


// print(updatePost(1))

// * Create a function that edits a given post. The user should be able to edit 
// * any object property he would like and should return the updated object
// * If the post is not found then the function should return 'Post not found'

function editPost(array, ids, property, newString) {
    let result;
    let notFound = 'The item not found'
    for (let index = 0; index < array.length; index++) {
        if (array[index].id === ids) {
            result = array[index]
            break;
        }
    }
    if (result === undefined) return notFound
    result[property] = newString
    return result
}

print(editPost(blogPosts, 2, 'title', 'Something Else'))